# Použij Node.js jako základní image
FROM node:16

# Nastav pracovní adresář v kontejneru
WORKDIR /app

# Zkopíruj package.json a package-lock.json
COPY package*.json ./

# Nainstaluj závislosti
RUN npm install

# Zkopíruj zbytek souborů do kontejneru
COPY . .

# Otevři port 3000 pro komunikaci
EXPOSE 3000

# Definuj příkaz, který spustí aplikaci
CMD ["npm", "start"]